### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by cannotkenpute** [therealOri/ChatterEye#1]
I get an error saying no module named tomllib found

**Comment by therealOri** [comment]
That would most likely be because tomllib is a builtin library (aka, by default already installed with python like "os".)

You shouldn't need to try and pip install tomllib if you are using the newer versions of python like 3.11+ - 3.12, etc. 


tomllib docs:
https://docs.python.org/3/library/tomllib.html



Would you be able to let me know what version of python you are using?

**Comment by cannotkenpute** [comment]
Thanks for the reply, I realized I did not have the right version of python, i figured it out myself

**Comment by therealOri** [comment]
Okay, sweet!


I'll be closing this now, and thanks for making an issue!
